// @ts-nocheck
// Auto-generated by FlowGen
import React from 'react';
export default function HomePage() {
  return (
    <div className="flowgen-page">
      <div className="min-h-screen bg-gradient-to-br from-blue-50 to-indigo-100 flex items-center justify-center">
  <div className="max-w-4xl mx-auto text-center px-4">
    <h1 className="text-5xl font-bold text-gray-900 mb-6">
      Welcome to Your App
    </h1>
    <p className="text-xl text-gray-600 mb-8 max-w-2xl mx-auto">
      A complete landing page for a fictional SaaS company called "InnovateAI".

The design should be modern, professional, and use a dark theme with green as the primary accent color.

- **Navbar:** A sticky navigation bar with the "InnovateAI" logo on the left. On the right, include links for "Solutions," "Pricing," and a highlighted "Request Demo" button.

- **Hero Section:** A large, centered headline that reads "Build Tomorrow's Software, Today." Below it, a short paragraph explaining how InnovateAI uses machine learning to accelerate development cycles. Include a prominent call-to-action button that says "Start Your Free Trial."

- **Features Section:** A three-column grid layout. Each column should be a card containing an icon, a title (e.g., "AI-Powered Debugging," "Automated Code Review," "Predictive Deployment"), and a brief description of the feature.
    </p>
    <div className="space-x-4">
      <button className="bg-blue-600 text-white px-8 py-3 rounded-lg font-medium hover:bg-blue-700 transition-colors">
        Get Started
      </button>
      <button className="bg-white text-blue-600 px-8 py-3 rounded-lg font-medium border border-blue-600 hover:bg-blue-50 transition-colors">
        Learn More
      </button>
    </div>
  </div>
</div>
    </div>
  );
}
